version: 0.2

phases:
build:
commands:
- dotnet test ./src/BeautifulRestApi.csproj
- dotnet publish -c release -o ./build_output ./src/BeautifulRestApi.csproj
artifacts:
files:
- src/HelloWorldWebCore/build_output/*
- appspec.yml
- install.ps1
- index.html
